config/routes.rb
Rails.application.routes.draw do
  get 'transmitted/index'
  root 'dashboard#index'

  resources :dashboard, only: [:index] do
    collection do
      get 'download_excel', as: "download_excel"
    end
  end
  get 'transmitted/index', to: 'transmitted#index', as: 'transmitted_index_with_params'


  resources :datasets, only: [] do
    collection do
      get 'inventory_files'
      get 'qc_files'
    end
  end

  resources :uploads, only: [:index]
  post '/upload', to: 'uploads#upload'
  post '/qc_upload', to: 'uploads#qc_upload'
  get '/delete/inventory_file/:filename', to: 'uploads#destroy_inventory_file', as: 'delete_inventory_file'
  get '/delete/qc_file/:filename', to: 'uploads#destroy_qc_file', as: 'delete_qc_file'
  get 'uploads/inventory_file/:filename', to: 'uploads#inventory_file', as: 'show_inventory_file_upload'
  get 'uploads/qc_file/:filename', to: 'uploads#qc_file', as: 'show_qc_file_upload'
  get '/download_excel_qc_file', to: 'uploads#download_excel_qc_file', as: 'download_excel_qc_file'
  get '/data', to: 'uploads#data'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :extract_year_and_month, only: [:index, :download_excel]

  def index
    @volume_data = volume_data
    @transmitted_data = transmitted_data
    @filing_data = filing_data
    @default_table = default_table_data
    @qc_score = qc_score
    @index_transmitted_table = TransmittedService.new(@year, @month).transmitted_tbl("index_date")
    @blank_party_transmitted_table = TransmittedService.new(@year, @month).transmitted_tbl("blank_party_date")
    @collateral_transmitted_table = TransmittedService.new(@year, @month).transmitted_tbl("collateral_date")
    @special_transmitted_table = TransmittedService.new(@year, @month).transmitted_tbl("special_date")
    @tax_lien_transmitted_table = TransmittedService.new(@year, @month).transmitted_tbl("tax_lien_date")
    @mdb_transmitted_table = TransmittedService.new(@year, @month).transmitted_tbl("mdb_date")
    @office_product_transmitted_table = TransmittedService.new(@year, @month).transmitted_tbl("office_product_date")
    @framed_scanned_transmitted_table = TransmittedService.new(@year, @month).transmitted_tbl("framed_scanned_date")
  end

  def download_excel
    year = params[:year]
    month = params[:month]
    trademark = params[:trademark]
    excel_data = excel_generator(month, year, trademark)
    send_data excel_data, filename: "#{trademark}_#{Time.now}.xlsx"
  end

  private

  def extract_year_and_month
    @year = params[:year]&.to_i || Time.now.year
    @month = params[:month]&.to_i || Time.now.month
  end

  def volume_data
    @volume_data ||= RemainingVolumeService.new(@month, @year).volume
  end

  def transmitted_data
    @transmitted_data ||= TransmittedService.new(@year, @month).transmittals_info
  end

  def filing_data
    @filing_data ||= FilingService.new(@month, @year).filing_info
  end

  def default_table_data
    @default_table_data ||= RemainingVolumeService.new(@month, @year).remaining_volume_tbl
  end

  def qc_score
    @qc_score ||= QcService.new(@year, @month).fetch_score
  end

  def excel_generator(month, year, trademark)
    @excel_generator ||= ExcelGeneratorService.new(month, year, trademark).generate_excel
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def transmitted_content(data, title)
    container = []
  
    data&.each do |item|
      item_data = {
        date_transmitted: item["#{title}_date"],
        units: item["#{title}_unit"],
        tat: item["tat_#{title}"],
        state_code: item["state_code"],
        date_received: item["date_received"],
        rider_no: item["rider_no"],
        coverage_date_from: item["coverage_date_from"],
        coverage_date_to: item["coverage_date_to"],
        volume: item["volume"]
      }
      container << item_data
    end
  
    container
  end

  def transmitted_header
    [
      "Date Transmitted", "Units", "TAT", "State Code", "Date Received", "Rider No",
      "Coverage Date-From", "Coverage Date-to", "No of Filings"
    ]
  end


  def remaining_volume_content(data)
    container = []
  
    data&.each do |item|
      item_data = {
        shipment: item['shipment'],
        date_received: item['date_received'],
        inventory_type: item['inventory_type'],
        state_code: item['state_code'],
        rider_no: item['rider_no'],
        coverage_date_from: item['coverage_date_from'],
        coverage_date_to: item['coverage_date_to'],
        volume: item['volume']
      }
      container << item_data
    end
  
    container
  end

  def remaining_volume_header
    [
      "Shipment", "Date Received", "Type", "State Code", "Rider No",
      "Coverage Date-From", "Coverage Date-to", "Volume"
    ]
  end
end

app/views/dashboard/_filing_tbl.html.erb
<div class="modal fade" id="<%= filing_modal_id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content modal-view">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= title %> </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body scroll">
        <table >
          <thead>
            <tr>
              <th>Date Transmitted</th>
              <th>Age</th>
              <th>State Code</th>
              <th>Date Received</th>
              <th>Rider No</th>
              <th>Coverage Date From</th>
              <th>Coverate Date To</th>
              <th>Ni of Filings Received</th>
            </tr>
          </thead>
          <tbody>
            <% filing_table&.each do |row| %>
              <tr>
                <td><%= row["#{title}_date"] %></td>   
                <td><%= row["days_old"] %></td>
                <td><%= row["state_code"] %></td>
                <td><%= row["date_received"] %></td>
                <td><%= row["rider_no:"] %></td>
                <td><%= row["coverage_date_from"] %></td>
                <td><%= row["coverage_date_to"] %></td>
                <td><%= row["volume"] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_qc_tbl.html.erb
<div class="modal fade " id="qc_table" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content modal-view">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Quality Score</h5>
        <%= link_to download_excel_dashboard_index_path(month: @month, year: @year, trademark: "QC"), 
            class: "px-2 btn btn-primary" do %>
          <i class="fas fa-download"></i>
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body scroll">
        <table >
          <thead>
            <tr>
              <th>UCC Transmission date</th>
              <th>Number of Filings</th>
              <th>Number of Errors (Critical)</th>
              <th>Number of Errors (Non-Critical)</th>
              <th>Qualty Score (Critical)</th>
              <th>Qualty Score (Non-Critical)</th>
              <th>Base Recs</th>
              <th>Debtor/Secured Party</th>
              <th>Collaterals</th>
            </tr>
          </thead>
          <tbody>

            <% @qc_score[:table]&.each do |file| %>
              <tr>
                <td><%= file['ucc_transmission_date'] %></td>
                <td><%= file['number_of_filing'] %></td>
                <td><%= file['no_of_error_critical'] %></td>
                <td><%= file['no_of_error_non_critical'] %></td>
                <td><%= string_percent(file['quality_score_critical']) %></td>
                <td><%= string_percent(file['quality_score_non_critical']) %></td>
                <td><%= file['base'] %></td>
                <td><%= file['debtor'] %></td>
                <td><%= file['collaterals'] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_transmitted_index_tbl.erb
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content modal-view">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= title %> </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
      <div class="modal-body scroll">
        <table >
          <thead>
            <tr>
              <th>Date Transmitted</th>
              <th>Units</th>
              <th>TAT</th>
              <th>State Code</th>
              <th>Date Received</th>
              <th>Rider No.</th>
              <th>Date Coverage From</th>
              <th>Date Coverage To</th>
              <th>No of Filings</th>
            </tr>
          </thead>
          <tbody>
            <% transmitted_data&.each do |row| %>
              <tr>
                <td><%= row["#{title}_date"] %></td>
                <td><%= row["#{title}_unit"] %></td>
                <td><%= row["tat_#{title}"] %></td>
                <td><%= row["state_code"] %></td>
                <td><%= row["date_received"] %></td>
                <td><%= row["rider_no"] %></td>
                <td><%= row["coverage_date_from"] %></td>
                <td><%= row["coverage_date_to"] %></td>
                <td><%= row["volume"] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_volume_tbl.html.erb
<div class="modal fade " id="exampleModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content modal-view">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Remaining Volume</h5>

        <%= link_to download_excel_dashboard_index_path(month: @month, year: @year, trademark: "Remaining Volume"), 
            class: "px-2 btn btn-primary" do %>
          <i class="fas fa-download"></i>
        <% end %>
        
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body scroll">
        <table >
          <thead>
            <tr>
              <th>Shipment</th>
              <th>Date Received</th>
              <th>Type</th>
              <th>State Code</th>
              <th>Rider No</th>
              <th>Coverage Date-From</th>
              <th>Coverage Date-to</th>
              <th>Volume</th>
            </tr>
          </thead>
          <tbody>
            <% @default_table.each do |row| %>
              <tr>
                <td><%= row['shipment'] %></td>
                <td><%= row['date_received'] %></td>
                <td><%= row['type'] %></td>
                <td><%= row['state_code'] %></td>
                <td><%= row['rider_no'] %></td>
                <td><%= row['coverage_date_from'] %></td>
                <td><%= row['coverage_date_to'] %></td>
                <td><%= row['volume'] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class='header'>
  <h1 class="title">Dashboard</h1>

  <div class="dashboard-data">
    <div class="filter">
      <%= form_tag(root_path, method: :get, data: { controller: "filter" }) do %>
        <div class="form-group">
          <%= select_tag(:month, options_for_select(Date::MONTHNAMES.compact.each_with_index.map { |name, i| [name, i + 1] }, @month), data: { target: "filter.month" }) %>
        </div>

        <div class="form-group">
          <%= select_tag(:year, options_for_select((2015..Date.today.year).to_a.reverse, @year), data: { target: "filter.year" }) %>
        </div>
        <% end %>
    </div>
  </div>
</div>

<div class='main-container'>
  <div class='box remaining'>
    <div class='box-item box1 '>
      <div class=' d-flex flex-row align-items-center card card-design'>
        <div class="icon-wrapper iwbg1">
          <i class="fa-regular fa-folder" style="color: #74C0FC;"></i>
        </div>

        <div class='box-data'>
          <h3 class='title1 text-start'>Volume</h3>
          <h3 class='value1'><%=  format_with_commas(@volume_data[:volume]) %> </h3>
        </div>
      </div>

      <div class='d-flex flex-row align-items-center card card-design'>
        <div class="icon-wrapper iwbg2">
          <i class="fa-regular fa-folder" style="color: #b39d4dd6;"></i>
        </div>

        <div class='box-data'>
          <h3 class='title1 text-start'>Remaining Volume</h3>
          <h3 class='value1'><%= format_with_commas(@volume_data[:remaining_volume]) %> </h3>
        </div>
      </div>
    </div>

    <div class='box-item card-design box2'>
      <div class='title'>Remaining Volume</div>

      <div class="flex-container" style="display: flex; flex-direction: column; height: 100%;">
        <div class="chart-container" data-controller="volume-type-chart" data-volume-type-chart-data-value="<%= @volume_data[:remaining_volume_tbl_grouped_by_type].to_json %>">
          <canvas id="rm-type" height="300"></canvas>
        </div>

        <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Remaining Volume Table
        </button>
        <%= render 'volume_tbl' %>
        <!-- 
        <div class="chart-container" data-controller="volume-statecode-chart" data-volume-statecode-chart-data-value="<%= @volume_data[:remaining_volume_tbl_grouped_by_statecode].to_json %>">
          <canvas id="rm-statecode" height="300"></canvas>
        </div> -->
       <!-- <%= button_to 'Launch static backdrop modal', '#', class: 'btn btn-primary text', data: { bs_toggle: 'modal', bs_target: '#staticBackdrop' } %> -->
      </div>
    </div>

    <div class='box-item card-design box3'>
      <h3 class='title'>Quality Score</h3>

      <div class='sub-card'>
        <div class='sub-card-info'>
          <h4 class='title1'>Critical</h4>
          <h3 class='value2'><%= @qc_score[:critical] %> </h3>
        </div>

        <div class='sub-card-info'>
          <h4 class='title1'>Non-critical</h4>
          <h3 class='value2'><%= @qc_score[:non_critical] %> </h3>
        </div>
      </div>

      <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#qc_table">
        click to see table
      </button>
      <%= render 'qc_tbl' %>
    </div>
  </div>
  
  <div class='box card-design'>
    <h3 class='title'>Volume Transmitted and TAT</h3>
    <div class='card-data'>
      <% @transmitted_data.each_with_index do |(title, data), index| %>
        <div class="card-info clickable" data-controller="clickable" 
            data-action="click->clickable#openModal" 
            data-target="clickable.modalTarget" 
            data-bs-toggle="modal" 
            data-bs-target="#transmitted_index_<%= index %>">
          <h4 class="title"><%= title.capitalize %></h4>
          
          <% if data[:sla].positive? %>
            <h3 class="sub-title">SLA: <%= data[:sla] %> Days</h3>
          <% end %>

          <div class="card-box">
            <div class="Unit">
              <h3 class="title">Unit</h3>
              <h3 class="value4"><%= data[:unit] %></h3>
            </div>
            <% if data[:sla].positive? %>
              <div class="TAT">
                <h3 class="title">Tat</h3>
                <h3 class="value4"><%= data[:tat] %></h3>
              </div>
            <% end %>
          </div>
        </div>

        <%= render 'transmitted_index_tbl', transmitted_data: data[:table], title: title, modal_id: "transmitted_index_#{index}" %>
      <% end %>
    </div>
  </div>

  <div class='box card-design filing'>
    <h3 class='title'>Volume Transmitted and TAT</h3>

    <div class='transmitted-container'>
      <p class="transmitted-title text-center">Index</p>
      <div class='transmitted-chart'>
        <div class="chart-container" data-controller="index-filing-chart" data-index-filing-chart-age-value="<%= @filing_data["index"][:chart].to_json %>">
          <canvas id="index-filing"  height ="180"></canvas>
        </div>

        <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#filing_modal_index">
          click to see table
        </button>
        <%= render 'filing_tbl', filing_table: @filing_data["index"][:table] , title: "index", filing_modal_id: "filing_modal_index" %>
      </div>
    </div>
  
    <div class='transmitted-container'>
      <p class="transmitted-title text-center">Collateral</p>
      <div class='chart' style="overflow-x: scroll">
        <div class="chart-container" data-controller="collateral-filing-chart" 
        data-collateral-filing-chart-age-value="<%= @filing_data["collateral"][:chart].to_json %>" 
        style="position: relative;  width:2000px;">
          <canvas id="collateral-filing"  height ="180"></canvas>
        </div>
        
        <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#filing_modal_collateral">
          click to see table
        </button>
        <%= render 'filing_tbl', filing_table: @filing_data["collateral"][:table] , title: "collateral", filing_modal_id: "filing_modal_collateral" %>
      </div>
    </div>

    <div class='transmitted-container'>
      <p class="transmitted-title text-center">Tax Lien</p>
      <div class='chart'>
        <div class="chart-container" data-controller="taxlien-filing-chart" data-taxlien-filing-chart-age-value="<%= @filing_data["tax_lien"][:chart].to_json %>">
          <canvas id="taxlien-filing"  height ="180"></canvas>
        </div>

        <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#filing_modal_tax_lien">
          click to see table
        </button>
        <%= render 'filing_tbl', filing_table: @filing_data["tax_lien"][:table] , title: "tax_lien", filing_modal_id: "filing_modal_tax_lien" %>
    </div>
  </div>
  </div>
</div>