config/routes.rb
Rails.application.routes.draw do
  get 'transmitted/index'
  root 'dashboard#index'

  resources :dashboard, only: [:index] do
    collection do
      get 'download_excel', as: "download_excel"
    end
  end
  get 'transmitted/index', to: 'transmitted#index', as: 'transmitted_index_with_params'


  resources :datasets, only: [] do
    collection do
      get 'inventory_files'
      get 'qc_files'
    end
  end

  resources :uploads, only: [:index]
  post '/upload', to: 'uploads#upload'
  post '/qc_upload', to: 'uploads#qc_upload'
  get '/delete/inventory_file/:filename', to: 'uploads#destroy_inventory_file', as: 'delete_inventory_file'
  get '/delete/qc_file/:filename', to: 'uploads#destroy_qc_file', as: 'delete_qc_file'
  get 'uploads/inventory_file/:filename', to: 'uploads#inventory_file', as: 'show_inventory_file_upload'
  get 'uploads/qc_file/:filename', to: 'uploads#qc_file', as: 'show_qc_file_upload'
  get '/download_excel_qc_file', to: 'uploads#download_excel_qc_file', as: 'download_excel_qc_file'
  get '/data', to: 'uploads#data'
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  UPLOADS_DIR = Rails.root.join('public', 'inventory_files')
  QC_UPLOADS_DIR = Rails.root.join('public', 'qc_files')

  def index
    @inventory_files = Inventory.all
    @qc_files = Qc.all
  end

  def qc_file
    filename = params[:filename]
    format = params[:format]
    filename = "#{filename}.#{format}"
    @qc_file_data = Qc.find_by(filename: filename).qc_item
  end

  def inventory_file
    filename = params[:filename]
    format = params[:format]
    filename = "#{filename}.#{format}"
    @data = Inventory.find_by(filename: filename).inventory_item
  end

  def upload
    files = params[:files]

    if files.present? && files.all? { |f| f.original_filename.ends_with?('.xlsx') }
      files.each do |file|
        if file.respond_to?(:original_filename) && file.respond_to?(:read)
          filename = file.original_filename
          file_path = File.join(UPLOADS_DIR, filename)
  

          if File.exist?(file_path)
            flash[:error] = "File '#{filename}' already exists."
            redirect_to uploads_path
            return
          else
            File.open(file_path, 'wb') do |f|
              f.write(file.read)
            end
            inventory = Inventory.new(filename: filename)
            if inventory.save
              parse_excel(file_path, inventory)
            end

          end
        end
      end

      flash[:notice] = "Files uploaded successfully."
      redirect_to uploads_path
    else
      flash[:error] = files.present? ? "Only .xlsx extension files are valid." : "No files detected."
      redirect_to uploads_path
    end
  end

  def qc_upload
    files = params[:files]

    if files.present? && files.all? { |f| f.original_filename.ends_with?('.xlsx') }
      files.each do |file|
        if file.respond_to?(:original_filename) && file.respond_to?(:read)
          filename = file.original_filename
          file_path = File.join(QC_UPLOADS_DIR, filename)

          if File.exist?(file_path)
            flash[:error] = "File '#{filename}' already exists."
            redirect_to uploads_path
            return
          else

            File.open(file_path, 'wb') do |f|
              f.write(file.read)
            end
            qc = Qc.new(filename: filename)
            if qc.save
              qc_parse_excel(file_path, filename, qc)
            end
          end
        end
      end

      flash[:notice] = "Files uploaded successfully."
      redirect_to uploads_path
    else
      flash[:error] = files.present? ? "Only .xlsx extension files are valid." : "No files detected."
      redirect_to uploads_path
    end

  end

  def destroy_inventory_file
    filename = params[:filename]
    fileformat =  params[:format]
    filename_with_extension = "#{filename}.#{fileformat}"
    Inventory.find_by(filename: filename_with_extension).destroy
    file_path = File.join(UPLOADS_DIR, filename_with_extension)
    if File.exist?(file_path)
      File.delete(file_path)
    else
      render plain: "File not found"
    end

    redirect_to uploads_path
  end

  def destroy_qc_file
    
    filename = params[:filename]
    fileformat =  params[:format]
    filename_with_extension = "#{filename}.#{fileformat}"
    Qc.find_by(filename: filename_with_extension).destroy
    file_path = File.join(QC_UPLOADS_DIR, filename_with_extension)
    if File.exist?(file_path)
      File.delete(file_path)
    else
      render plain: "File not found"
    end

    redirect_to uploads_path
  end

  def parse_excel(file_path, inventory)
    excel = Roo::Spreadsheet.open(file_path)
    data = []
  
    (3..excel.last_row).each do |i|
      row = excel.row(i)
      inventory_item = inventory.inventory_item.create(
        shipment: row[0],
        date_received: row[1],
        inventory_type: row[2],
        state_code: row[3],
        rider_no: row[4],
        coverage_date_from: row[5],
        coverage_date_to: row[6],
        volume: row[7],
        index_unit: row[8],
        index_date: row[9],
        blank_party_unit: row[10],
        blank_party_date: row[11],
        collateral_unit: row[12],
        collateral_date: row[13],
        special_unit: row[14],
        special_date: row[15],
        tax_lien_unit: row[16],
        tax_lien_date: row[17],
        frame_scanned_unit: row[18],
        frame_scanned_date: row[19],
        mdb_unit: row[20],
        mdb_date: row[21],
        office_product_unit: row[22],
        office_product_date: row[23],
        tat_index: row[24],
        tat_blank_party: row[25],
        tat_collateral: row[26],
        tat_special: row[27],
        tat_tax_lien: row[28],
        tat_mdb: row[29],
        tat_office_product: row[30]
      )
  
      update_volume_status(inventory_item)
      update_days_old(inventory_item)

    end
  
    data
  end
  
  def update_volume_status(inventory_item)
    date_fields = ["index_date", "blank_party_date", "collateral_date", "special_date", "tax_lien_date", "frame_scanned_date", "mdb_date", "office_product_date"]
    if date_fields.any? { |field| inventory_item[field].present? && !!Date.strptime(inventory_item[field], '%Y-%m-%d') rescue false }
    inventory_item.update_column(:volume_status, 'Process')
    else
      inventory_item.update_column(:volume_status, 'Remaining')
    end
  end
  
  def update_days_old(inventory_item)
    if inventory_item.date_received && inventory_item.coverage_date_from
      inventory_item.days_old = (inventory_item.date_received - inventory_item.coverage_date_from).to_i
      inventory_item.save
    end
  end

  def qc_parse_excel(file_path, filename, qc)
    excel = Roo::Spreadsheet.open(file_path)
    data = []
  
    (7..excel.last_row).each do |i|
      row = excel.row(i)
      qc_item = qc.qc_item.create(
        ucc_transmission_date: row[0],
        number_of_filing: row[1],
        no_of_error_critical: row[2],
        no_of_error_non_critcal: row[3],
        quality_score_critical: row[4],
        quality_score_non_critical: row[5],
        base: row[6],
        debtor: row[7],
        collaterals: row[8]
      )

      update_month_year(qc_item, filename)
    end

    data = []
  end

  def update_month_year(qc_item, filename)
    match_data = filename.match(/(\w{3}) '(\d{4})/)
    month = match_data[1]
    year = match_data[2]
    month_year = "#{month} #{year}"
    qc_item.update_column(:month_year, month_year)
  end
end  

app/helpers/uploads_helper.rb
module UploadsHelper
  def filename_without_extension(file)
    File.basename(file, File.extname(file))
  end
end

app/views/uploads/index.html.erb
<% flash.each do |key, value| %>
  <div class="notification <%= key %>" data-controller="notification">
    <% if key == 'error' %>
      <i class="fas fa-exclamation-triangle"></i>
    <% end %>
    <%= value %>
    <button class="close-btn" data-action="notification#close">&times;</button>
  </div>
<% end %>

<div class="data">
  <div class="content-data inventory">
    <div class='left-card'>
      <h3>Inventory Files</h3>
      <table class="uploaded-files-table">
        <thead>
          <tr>
            <th>File Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @inventory_files.each do |file| %>
            <tr>

              <td><%= link_to file.filename, show_inventory_file_upload_path(file.filename) %> </td>
              <td>
                <div class="file-actions">
                  <%= link_to delete_inventory_file_path(file.filename), method: :delete, class: "delete-link", data: { turbo_confirm: "Are you sure?" } do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table >
    </div>

    <div class='upload-files'>
      <%= form_tag(upload_path, multipart: true) do %>
        <div class="drop_data drag-drop-box" data-controller="file-upload"  data-action="click->file-upload#triggerInput">
          <label for="file-upload-input" class="file-upload-label">
            Click to add files
          </label>
          <%= file_field_tag 'files[]', multiple: true, class: "file-input", id: "file-upload-input" %>
        </div>
        <div class="file-list">
          <ul data-target="file-upload.output"></ul>
        </div>
      <% end %>
    
    </div>
  </div>

  <div class="content-data inventory">
    <div class='left-card'>
      <h3>QC Files</h3>
      <table class="uploaded-files-table">
        <thead>
          <tr>
            <th>File Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @qc_files.each do |file| %>
            <tr>
              <td><%= link_to file.filename, show_qc_file_upload_path(file.filename) %> </td>
              <td>
                <div class="file-actions">
                  <%= link_to delete_qc_file_path(file.filename), method: :delete, class: "delete-link", data: { turbo_confirm: "Are you sure?" } do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table >
    </div>

    <div class='upload-files'>
      <%= form_tag(qc_upload_path, multipart: true) do %>
        <div class="drop_data drag-drop-box" data-controller="file-upload"  data-action="click->file-upload#triggerInput">
          <label for="file-upload-input" class="file-upload-label">
            Click to add files
          </label>
          <%= file_field_tag 'files[]', multiple: true, class: "file-input", id: "file-upload-input" %>
        </div>
        <div class="file-list">
          <ul data-target="file-upload.output"></ul>
        </div>
      <% end %>
    
    </div>
  </div>
</div>

app/views/uploads/inventory_file.html.erb
<div class='upload-container card-design'>
<div class="head">
  <h2><%= link_to uploads_path do %>
    <span class="circle-left-icon" title="go back">
      <i class="fas fa-circle-left"></i>
    </span>
  <% end %><%= @filename%> </h2>
</div>

<div class='scroll'>
  <table >
    <thead>
      <tr>
        <th>Shipment</th>
        <th>Date Received</th>
        <th>Type</th>
        <th>State Code</th>
        <th>Rider No</th>
        <th>Coverage Date-From</th>
        <th>Coverage Date-to</th>
        <th>Volume</th>
        <th>Index Unit</th>
        <th>Index Date</th>
        <th>Blank Party-Unit</th>
        <th>Blank Party-Date</th>
        <th>Collateral-unit</th>
        <th>Collateral-date</th>
        <th>Special-Unit</th>
        <th>Special-Date</th>
        <th>Tax Lien-Unit</th>
        <th>Tax Lien-Date</th>
        <th>Frame Scanned-Unit</th>
        <th>Frame Scanned-Date</th>
        <th>MDB-Unit</th>
        <th>MDB-Date</th>
        <th>Office Product-Unit</th>
        <th>Office Product-Date</th>
        <th>TAT-Index</th>
        <th>TAT-Blank Party</th>
        <th>TAT-Collateral</th>
        <th>TAT-Special</th>
        <th>TAT-Tax Lien</th>
        <th>TAT-MDB</th>
        <th>TAT-Office Product</th>
      </tr>
    </thead>
    <tbody>
      <% @data.each do |row| %>
        <tr>
          <td><%= row['shipment'] %></td>
          <td><%= row['date_received'] %></td>
          <td><%= row['type'] %></td>
          <td><%= row['state_code'] %></td>
          <td><%= row['rider_no'] %></td>
          <td><%= row['coverage_date_from'] %></td>
          <td><%= row['coverage_date_to'] %></td>
          <td><%= row['volume'] %></td>
          <td><%= row['index_unit'] %></td>
          <td><%= row['index_date'] %></td>
          <td><%= row['blank_party_unit'] %></td>
          <td><%= row['blank_party_date'] %></td>
          <td><%= row['collateral_unit'] %></td>
          <td><%= row['collateral_date'] %></td>
          <td><%= row['special_unit'] %></td>
          <td><%= row['special_date'] %></td>
          <td><%= row['tax_lien_unit'] %></td>
          <td><%= row['tax_lien_date'] %></td>
          <td><%= row['frame_scanned_unit'] %></td>
          <td><%= row['frame_scanned_date'] %></td>
          <td><%= row['mdb_unit'] %></td>
          <td><%= row['mdb_date'] %></td>
          <td><%= row['office_product_unit'] %></td>
          <td><%= row['office_product_date'] %></td>
          <td><%= row['tat_index'] %></td>
          <td><%= row['tat_blank_party'] %></td>
          <td><%= row['tat_collateral'] %></td>
          <td><%= row['tat_special'] %></td>
          <td><%= row['tat_tax_lien'] %></td>
          <td><%= row['tat_mdb'] %></td>
          <td><%= row['tat_office_product'] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/uploads/qc_file.html.erb
<div class='upload-container card-design'>
  <div class="head">
    <h2><%= link_to uploads_path do %>
      <span class="circle-left-icon" title="go back">
        <i class="fas fa-circle-left"></i>
      </span>
    <% end %><%= @qc_filename %> </h2>
  </div>
  <div class='scroll'>  
    <table>
      <thead>
        <tr>
          <th>UCC Transmission date</th>
          <th>Number of Filings</th>
          <th>Number of Errors (Critical)</th>
          <th>Number of Errors (Non-Critical)</th>
          <th>Qualty Score (Critical)</th>
          <th>Qualty Score (Non-Critical)</th>
          <th>Base Recs</th>
          <th>Debtor/Secured Party</th>
          <th>Collaterals</th>
        </tr>
      </thead>
      <tbody>
        <% @qc_file_data.each do |file| %>
          <tr>
            <td><%= file['ucc_transmission_date'] %></td>
            <td><%= file['number_of_filing'] %></td>
            <td><%= file['no_of_error_critical'] %></td>
            <td><%= file['no_of_error_non_critcal'] %></td>
            <td><%= string_percent(file['quality_score_critical']) %></td>
            <td><%= string_percent(file['quality_score_non_critical']) %></td>
            <td><%= file['base'] %></td>
            <td><%= file['debtor'] %></td>
            <td><%= file['collaterals'] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>