config/routes.rb
Rails.application.routes.draw do
  get 'transmitted/index'
  root 'dashboard#index'

  resources :dashboard, only: [:index] do
    collection do
      get 'download_excel', as: "download_excel"
    end
  end
  get 'transmitted/index', to: 'transmitted#index', as: 'transmitted_index_with_params'


  resources :datasets, only: [] do
    collection do
      get 'inventory_files'
      get 'qc_files'
    end
  end

  resources :uploads, only: [:index]
  post '/upload', to: 'uploads#upload'
  post '/qc_upload', to: 'uploads#qc_upload'
  get '/delete/inventory_file/:filename', to: 'uploads#destroy_inventory_file', as: 'delete_inventory_file'
  get '/delete/qc_file/:filename', to: 'uploads#destroy_qc_file', as: 'delete_qc_file'
  get 'uploads/inventory_file/:filename', to: 'uploads#inventory_file', as: 'show_inventory_file_upload'
  get 'uploads/qc_file/:filename', to: 'uploads#qc_file', as: 'show_qc_file_upload'
  get '/download_excel_qc_file', to: 'uploads#download_excel_qc_file', as: 'download_excel_qc_file'
  get '/data', to: 'uploads#data'
end

app/views/layouts/_navbar.html.erb
<nav data-controller="sidebar">
  <i class='bx bx-menu toggle-sidebar' data-action="click->sidebar#toggleSidebar"></i>
  
  <form action="#">
    <div class="form-group">
      <input type="text" placeholder="Search...">
      <i class='bx bx-search icon' ></i>
    </div>
  </form>
  <a href="#" class="nav-link">
    <i class='bx bxs-bell icon' ></i>
    <span class="badge">5</span>
  </a>
  <span class="divider"></span>
  <div class="profile">
    <img src="https://scontent.filo1-1.fna.fbcdn.net/v/t1.6435-1/144138354_193709152497483_1907776020397923435_n.jpg?stp=c20.0.200.200a_dst-jpg_p200x200&_nc_cat=111&ccb=1-7&_nc_sid=5f2048&_nc_ohc=HMtLKjXXI7YQ7kNvgH88DAt&_nc_ht=scontent.filo1-1.fna&oh=00_AYDEQCFhpsjSbhdvzfx7lG9ZgeXjEFrdJlVAN6y4vRL12Q&oe=6669AEC8" alt="">
    <ul class="profile-link">
      <li><a href="#"><i class='bx bxs-user-circle icon' ></i> Profile</a></li>
      <li><a href="#"><i class='bx bxs-cog' ></i> Settings</a></li>
      <li><a href="#"><i class='bx bxs-log-out-circle' ></i> Logout</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<section id="sidebar">
  <a href="#" class="brand"><i class='bx bxs-smile icon'></i>UCC</a>
  <ul class="side-menu">
    <li><%= content_tag :li, class: "link" do %>
          <%= link_to root_path, class: "active" do %>
            <i class='fas fa-chart-column icon'></i> Dashboard 
          <% end %>
        <% end %></li>
    <li class="divider" data-text="main">Main</li>
    <li>
      <%= link_to inventory_files_datasets_path, class: "link", data: { action: "click->sidebar#dropdown" } do %>
            <i class="fas fa-database icon"></i>Datasets
          <% end %>
      <ul class="side-dropdown show">
        <li><%= link_to "Inventory", inventory_files_datasets_path, class: "active" %></li>
        <li><%= link_to "QC", qc_files_datasets_path, class: "active" %></li>
      </ul>
    </li>
    <li><%= link_to uploads_path, class:"link" do %>
            <i class="icon fas fa-upload"></i> Uploads
          <% end %></li>
  </ul>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UccPrototype</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">


  </head>

  <body>
    <%= render 'layouts/sidebar' %>
    <section id="content">
      <%= render 'layouts/navbar' %>
      <main>
        <%= yield %>  
      </main>
    </section>
  </body>
</html>